// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4DTIENNj3bDvnyiDPLEwSb5Qtj91WveE',
    appId: '1:100441927901:web:87c81c138eedaac42eab34',
    messagingSenderId: '100441927901',
    projectId: 'room-rover-r-resrv-be',
    authDomain: 'room-rover-r-resrv-be.firebaseapp.com',
    storageBucket: 'room-rover-r-resrv-be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjNucT-Q0hW83CoYXzJDuBQb1oeu-COFQ',
    appId: '1:100441927901:android:47eff9db185c5ce32eab34',
    messagingSenderId: '100441927901',
    projectId: 'room-rover-r-resrv-be',
    storageBucket: 'room-rover-r-resrv-be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKncAutcxT3z6w23C0PMwj1FhwWh_u-as',
    appId: '1:100441927901:ios:49ef249ac5e4f6062eab34',
    messagingSenderId: '100441927901',
    projectId: 'room-rover-r-resrv-be',
    storageBucket: 'room-rover-r-resrv-be.appspot.com',
    iosBundleId: 'com.example.roomRover',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKncAutcxT3z6w23C0PMwj1FhwWh_u-as',
    appId: '1:100441927901:ios:9dfb7bebc7fa86fb2eab34',
    messagingSenderId: '100441927901',
    projectId: 'room-rover-r-resrv-be',
    storageBucket: 'room-rover-r-resrv-be.appspot.com',
    iosBundleId: 'com.example.roomRover.RunnerTests',
  );
}
